apiVersion: v1
kind: Secret
metadata:
  name: bankdb-credentials
  namespace: exbanka-db
  labels:
    app.kubernetes.io/name: exbanka-postgres
    app.kubernetes.io/part-of: exbanka
type: kubernetes.io/basic-auth
stringData:
  username: exbanka_app
  password: change-me
