apiVersion: v1
kind: Secret
metadata:
  name: exbanka-app-secrets
  namespace: exbanka
  labels:
    app.kubernetes.io/part-of: exbanka
type: Opaque
stringData:
  DB_USER: exbanka_app
  DB_PASSWORD: change-me
  JWT_SECRET: change-me
  ALPHA_VANTAGE_KEY: change-me
  REDIS_PASSWORD: change-me
