apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: exbanka
  labels:
    app.kubernetes.io/name: exbanka-redis
    app.kubernetes.io/part-of: exbanka
type: Opaque
stringData:
  redis-password: change-me
