events {}

http {

    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth-service:8080/;
        }

        location /employees/ {
            proxy_pass http://employee-service:8080/;
        }

        location /notifications/ {
            proxy_pass http://notification-service:8080/;
        }

        location / {
            return 200 "EXBanka infrastructure running";
        }

    }

}